# Generated by Django 3.0.6 on 2020-06-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_choosegoals_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosegoals',
            name='goal',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
    ]
