# Generated by Django 3.0.6 on 2020-06-07 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_auto_20200607_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victim_request', to=settings.AUTH_USER_MODEL)),
                ('out_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
